language: java
sudo: false
jdk:
  - oraclejdk8
install: 
  - "mvn -N io.takari:maven:wrapper -Dmaven=3.3.3"
  - "./mvnw --show-version --errors --batch-mode --file java/pom.xml test-compile dependency:go-offline"
script: "./mvnw --show-version --errors --batch-mode --file java/pom.xml clean verify site"
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - mfriedenhagen@gmail.com
