language: java
sudo: false
jdk:
  - oraclejdk8
install: 
  - "mvn --non-recursive --quiet io.takari:maven:wrapper -Dmaven=3.3.9"
script: "./mvnw --file java/pom.xml clean verify site"
cache:
    directories:
    - $HOME/.m2
branches:
    except:
        - gh-pages
notifications:
    email:
        - mfriedenhagen@gmail.com
